---
run:
  concurrency: 3
  timeout: 15m
  issues-exit-code: 1
  tests: true
  # list of build tags, all linters use it. Default is empty list

# output configuration options
output:
  # print lines of code with issue, default is true
  print-issued-lines: true
  # print linter name in the end of issue text, default is true
  print-linter-name: true
  uniq-by-line: false

# all available settings of specific linters
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/tj/assert"
            desc: not allowed, did you mean testify assert?
          - pkg: "log"
            desc: Use 'log "github.com/sirupsen/logrus"' instead
  errcheck:
    check-type-assertions: false
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default
      - prefix(github.com/wimspaargaren/prolayout)
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # AllowList
          - [] # DenyList
      - name: argument-limit
        severity: warning
        disabled: true
      - name: banned-characters
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: file-header
        disabled: true
      - name: cognitive-complexity
        disabled: false
        arguments: [15]
      - name: unused-receiver
        disabled: true
      - name: function-length
        disabled: false
        arguments: [30, 0]
      - name: line-length-limit
        disabled: true
      - name: cyclomatic
        disabled: false
        arguments: [7]
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments: [3]
      - name: import-alias-naming
        severity: warning
        disabled: false
        arguments:
          - "^[a-z][a-z0-9A-Z]{0,}$"
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 175
  goconst:
    min-len: 3
    min-occurrences: 3
  funlen:
    lines: 80
    statements: 50
  godox:
    keywords:
      - HACK
      - OPTIMIZE
      - TODO
      - BUG
  misspell:
    locale: UK
    ignore-words:
      - color
      - center
      - centers
  lll:
    line-length: 200
    tab-width: 2
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 0
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    disabled-checks:
      - regexpMust
    enabled-tags:
      - performance
    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32

linters:
  enable-all: true
  disable:
    - errname
    - execinquery # deprecated (since v1.58.0)
    - exhaustruct
    - exportloopref # deprecated (since v1.60.2)
    - gomnd # deprecated (since v1.58.0)
    - nilnil
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wsl

  fast: false

severity:
  default-severity: error
  rules:
    - linters:
        - gomodguard
      severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      text: "^//go:generate "
    - linters:
        - revive
      path: internal/analyzer/analyzer.go
      text: "cyclomatic: function \\(\\*runner\\).assessDir has cyclomatic complexity 8 \\(\\> max enabled 7\\)"

  exclude-use-default: false

  max-issues-per-linter: 0

  max-same-issues: 0

  new: false
