---
name: Golang
"on":
  # required by gomod-go-version-updater to trigger this action once pr has
  # been reviewed
  pull_request_review:
    types: [submitted]
  push:
permissions:
  contents: read
  packages: read
jobs:
  #
  mcvs-golang-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: schubergphilis/mcvs-golang-action@87-optional-gci
        with:
          code_coverage_expected: 59.8
          gci: "false"
          golang-unit-tests-exclusions: |-
            \(cmd\/mcvs-scanner\|cmd\/mcvs-scanner-cli\|deprecated\|docs\/swagger\|mocks\)
          golangci-lint-version: v1.61.0
